// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241017214418_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Choices.Choice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("choice_id");

                    b.Property<int>("Move")
                        .HasColumnType("integer")
                        .HasColumnName("move");

                    b.HasKey("Id")
                        .HasName("pk_choices");

                    b.ToTable("choices", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("525ca1e4-3e8c-437c-b505-064bf63ad6f8"),
                            ChoiceId = 1,
                            Move = 1
                        },
                        new
                        {
                            Id = new Guid("42c55ad4-f082-4289-9460-4880da57d77f"),
                            ChoiceId = 2,
                            Move = 2
                        },
                        new
                        {
                            Id = new Guid("038a9e62-7c05-42af-b85b-7050d14b6fc3"),
                            ChoiceId = 3,
                            Move = 3
                        },
                        new
                        {
                            Id = new Guid("9abf55d1-8f8a-43a9-89e1-db6dc53fd27a"),
                            ChoiceId = 4,
                            Move = 4
                        },
                        new
                        {
                            Id = new Guid("d032be8a-5260-4652-a047-ca5e1bb2ed47"),
                            ChoiceId = 5,
                            Move = 5
                        });
                });

            modelBuilder.Entity("Domain.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComputerChoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("computer_choice_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GameResult")
                        .HasColumnType("integer")
                        .HasColumnName("game_result");

                    b.Property<Guid>("PlayerChoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_choice_id");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("ComputerChoiceId")
                        .HasDatabaseName("ix_games_computer_choice_id");

                    b.HasIndex("GameResult")
                        .HasDatabaseName("ix_games_game_result");

                    b.HasIndex("PlayerChoiceId")
                        .HasDatabaseName("ix_games_player_choice_id");

                    b.ToTable("games", "public");
                });

            modelBuilder.Entity("Domain.Games.Game", b =>
                {
                    b.HasOne("Domain.Choices.Choice", "ComputerChoice")
                        .WithMany()
                        .HasForeignKey("ComputerChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_choices_computer_choice_id");

                    b.HasOne("Domain.Choices.Choice", "PlayerChoice")
                        .WithMany()
                        .HasForeignKey("PlayerChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_choices_player_choice_id");

                    b.Navigation("ComputerChoice");

                    b.Navigation("PlayerChoice");
                });
#pragma warning restore 612, 618
        }
    }
}
